backup_dir: /media/data/Backup
drives:
  - uuid: f2a67f5e-4752-4ebb-a86b-8e0fb0fca58f
    mount_point: /media/data
    fs_type: auto
    options: nosuid,nodev,nofail,x-gvfs-show
apt_repos:
  - key: vscode
    source: https://packages.microsoft.com/repos/vscode stable main
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    key_name: microsoft
  - key: sublime-text
    source: https://download.sublimetext.com/ apt/stable/
    key_url: https://download.sublimetext.com/sublimehq-pub.gpg
    key_name: sublime-text
  - key: brave-browser
    source: https://brave-browser-apt-release.s3.brave.com/ stable main
    key_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    key_name: brave-browser
  - key: dbeaver
    source: https://dbeaver.io/debs/dbeaver-ce /
    key_url: https://dbeaver.io/debs/dbeaver.gpg.key
    key_name: dbeaver
  - key: spotify
    source: http://repository.spotify.com stable non-free
    key_url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    key_name: spotify
  - key: plexmediaserver
    source: https://downloads.plex.tv/repo/deb public main
    key_url: https://downloads.plex.tv/plex-keys/PlexSign.key
    key_name: plexmediaserver
  - key: docker
    source: https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    key_url: https://download.docker.com/linux/ubuntu/gpg
    key_name: docker
apt_ppa_repos:
  - ppa:papirus/papirus
apt_packages:
  - jq
  - gir1.2-gtop-2.0
  - lm-sensors
  - gir1.2-gmenu-3.0
  - htop
  - zsh
  - neofetch
  - chrome-gnome-shell
  - gnome-tweaks
  - dconf-editor
  - papirus-icon-theme
  - vim
  - tilix
  - code
  - sublime-text
  - brave-browser
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - dbeaver-ce
  - gnote
  - flameshot
  - meld
  - spotify-client
  - plexmediaserver
  - vlc
  - steam
gnome_extensions:
  - key: arcmenu
    name: ArcMenu
    package: arcmenuarcmenu.com.v17.shell-extension.zip
    schema: org.gnome.shell.extensions.arcmenu
  - key: blur-my-shell
    name: Blur my Shell
    package: blur-my-shellaunetx.v22.shell-extension.zip
    schema: org.gnome.shell.extensions.blur-my-shell
  - key: emoji-selector
    name: Emoji Selector
    package: emoji-selectormaestroschan.fr.v20.shell-extension.zip
    schema: org.gnome.shell.extensions.emoji-selector
  - key: floating-dock
    name: Floating Dock
    package: floating-docknandoferreira_profhotmail.com.v1.shell-extension.zip
    schema: org.gnome.shell.extensions.dash-to-dock
  - key: sound-output-device-chooser
    name: Sound Input & Output Device Chooser
    package: sound-output-device-chooserkgshank.net.v38.shell-extension.zip
    schema: org.gnome.shell.extensions.sound-output-device-chooser
  - key: status-area-horizontal-spacing
    name: Status Area Horizontal Spacing
    package: status-area-horizontal-spacingmathematical.coffee.gmail.com.v16.shell-extension.zip
    schema: org.gnome.shell.extensions.status-area-horizontal-spacing
  - key: user-themes
    name: User Themes
    package: user-themegnome-shell-extensions.gcampax.github.com.v40.shell-extension.zip
    schema: org.gnome.shell.extensions.user-theme
  - key: vitals
    name: Vitals
    package: VitalsCoreCoding.com.v39.shell-extension.zip
    schema: org.gnome.shell.extensions.vitals
  - key: workspaces-bar
    name: Workspaces Bar
    package: workspaces-barfthx.v11.shell-extension.zip
    schema:
